# Generated by Django 3.2.5 on 2021-07-23 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('surname', models.CharField(max_length=150, verbose_name='surname')),
                ('works', models.IntegerField(blank=True, verbose_name='all works')),
                ('money', models.IntegerField(blank=True, verbose_name='money')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('surname', models.CharField(max_length=150, verbose_name='surname')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_pro', to=settings.AUTH_USER_MODEL)),
                ('workers', models.ManyToManyField(blank=True, to='accounts.Workers', verbose_name='workers')),
            ],
        ),
    ]
