# Generated by Django 3.2.5 on 2021-07-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='money',
            field=models.IntegerField(default=0, verbose_name='money'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='works',
            field=models.IntegerField(default=0, verbose_name='all works'),
        ),
    ]
